export const livePage = String.raw`<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Luma · Real AI locally</title>
<style>
:root{font:16px/1.5 system-ui,sans-serif;color:#0B1020;background:#EEF2F8}*{box-sizing:border-box}body{margin:0}main{max-width:1120px;margin:auto;padding:28px}h1{font-size:30px;letter-spacing:-1px;margin:0}h2{font-size:20px;margin-top:0}h3{font-size:16px}p{margin:10px 0}.muted,small{color:#65708A}small{display:block}.top{display:flex;justify-content:space-between;gap:20px;align-items:center}.badge{background:#e0e9ff;border-radius:30px;padding:8px 15px;color:#214dbb}.grid{display:grid;grid-template-columns:1fr 1fr;gap:20px}.card{padding:22px;background:#fff;border:1px solid #dce3ef;border-radius:16px;margin:20px 0}label{display:block;font-weight:600;font-size:14px;margin:12px 0 5px}input,textarea,select,button{font:inherit;max-width:100%}input,textarea,select{width:100%;border:1px solid #bdc7d9;border-radius:8px;padding:10px;background:white;color:inherit}textarea{min-height:240px;resize:vertical}button{padding:9px 14px;border:1px solid #c8d1e1;border-radius:8px;background:white;color:inherit;margin:10px 5px 0 0;cursor:pointer}button.primary{background:#2563FF;color:white;border-color:#2563FF}button:disabled{opacity:.5;cursor:not-allowed}button:focus-visible,input:focus-visible,textarea:focus-visible,select:focus-visible{outline:3px solid #aabfff;outline-offset:2px}pre{white-space:pre-wrap;overflow-wrap:anywhere;font-size:12px;background:#f4f6fa;padding:12px;border-radius:8px;max-height:420px;overflow:auto}details{margin:12px 0}summary{cursor:pointer;font-weight:600}.item{border-top:1px solid #e3e7ef;padding:12px 0}.item p{margin:3px 0}.answer{white-space:pre-wrap}.error{color:#aa273a}.usage{font-size:14px}.notice{padding:12px 16px;border-left:3px solid #5B4DFF;background:white;margin:18px 0}#status{min-height:28px;font-weight:600}@media(max-width:760px){main{padding:16px}.grid{grid-template-columns:1fr}.top{align-items:flex-start;flex-direction:column}.card{margin:12px 0}}
</style></head><body><main>
<div class="top"><h1>Luma / Real AI locally</h1><span class="badge">Runs on your Mac · AI calls can cost money</span></div>
<p class="muted">Paste a conversation, get real AI analysis, and ask about the evidence. This uses Luma's production AI adapters and core, with external writes disabled.</p>
<p id="status" role="status" aria-live="polite">Loading…</p>
<section class="card"><h2>Connection and usage</h2><div id="usage" class="usage"></div>
<label for="key">OpenAI API key</label><input id="key" type="password" autocomplete="off" spellcheck="false" placeholder="Paste your key here, not into the chat"><button id="connect">Use key for this session</button><button id="disconnect">Disconnect</button>
<small>The key is sent only to this local server, kept in memory, and used to authenticate requests to OpenAI. It is not saved in browser storage or the database. Connecting makes no AI call.</small>
</section>
<div class="notice">Only text you submit here is used. AI requests send that text and the relevant local meeting context to OpenAI. Your inputs, corrections and usage records are retained locally across restarts. This does not connect to Discord, Notion, Linear or Granola.</div>
<div class="grid"><section>
<div class="card"><h2>1. Analyze a conversation</h2><label for="title">Meeting title</label><input id="title" value="Local Luma test" maxlength="120">
<label for="source">Conversation or meeting text</label><textarea id="source" maxlength="12000" placeholder="Paste German, English or mixed meeting text. Include names where they matter; pasted speaker labels are not independently verified."></textarea>
<button id="sample">Insert example</button><button id="analyze" class="primary">Analyze with real AI</button><small>Up to 12,000 characters. Relative dates use the submission time in Europe/Berlin. Each analysis creates a new local meeting and can incur a charge.</small></div>
<div class="card"><h2>Stored local meetings</h2><label for="meeting">Choose a meeting</label><select id="meeting"></select><button id="select">Open meeting</button><button id="replay">Replay source event</button><button id="conclude">Conclude meeting</button><small>Opening, replaying an accepted event and concluding use stored state without paid AI. Replays do not retry failed AI analysis.</small><details><summary>Original submitted source</summary><pre id="original"></pre></details></div>
<div class="card"><h2>Human corrections</h2><label for="item">Action or decision</label><select id="item"></select><button id="confirm">Confirm</button><button id="reject">Reject</button><label for="owner">Action owner</label><select id="owner"><option value="person_jakob">Jakob</option><option value="person_fabius">Fabius</option><option value="person_philipp">Philipp</option><option value="person_julius">Julius</option></select><button id="change-owner">Change owner</button><small>Acts as Jakob in this local test. Corrections cost no AI usage. Follow-up questions receive your original correction instructions.</small></div>
</section><section>
<div class="card"><h2>2. Ask Luma with real AI</h2><label for="question">Question about the selected conversation</label><input id="question" maxlength="2000" value="What did we decide, and what is still uncertain?"><button id="ask" class="primary">Ask with real AI</button><div id="answer" class="answer"></div><div id="citations"></div><small>Answers use your pasted source and explicit corrections. No live organizational retrieval or web search is enabled. An unchanged repeated question reuses its stored answer when available.</small></div>
<div class="card"><h2>Current understanding</h2><div id="items"></div><details><summary>Full meeting state</summary><pre id="state"></pre></details></div>
<div class="card"><h2>Last operation</h2><div id="outcome"></div><details><summary>Full receipt</summary><pre id="receipt"></pre></details></div>
<div class="card"><h2>Test allowance</h2><p>Initial cap: <strong>$1 per calendar month</strong> in Europe/Berlin, with at most $0.05 reserved per AI workflow. Restarting or changing checkouts does not reset it.</p><p>Amounts are calculated from reported tokens and Luma's configured rates, not your provider invoice. Unknown charges stay reserved. No automatic retries, budget increases, tools or external writes.</p><small>This local ledger does not aggregate other apps or a separate production deployment. Reconcile local usage into the agreed $30 total before enabling concurrent production usage. Live model quality and correctness still need your review.</small></div>
</section></div></main><script>
const el=id=>document.getElementById(id);const node=(tag,text,cls)=>{const n=document.createElement(tag);n.textContent=text;if(cls)n.className=cls;return n;};const pretty=v=>JSON.stringify(v,null,2);let current=null,busy=false;
const money=n=>'$'+Number(n||0).toFixed(5);
function lock(value){busy=value;document.querySelectorAll('button').forEach(b=>b.disabled=value);if(!value){el('analyze').disabled=!current?.connected;el('ask').disabled=!current?.connected||!current?.selected;}}
function render(data){current=data;const u=data.usage;el('usage').textContent=data.model+' · '+(data.connected?'Key loaded':'No key configured')+' · '+u.status+' · spent '+money(u.spentUsd)+' · pending '+money(u.reservedUsd)+' · uncertain '+money(u.unknownUsd)+' · '+u.requestCount+' requests · limit $'+u.monthlyLimitUsd+' · resets '+u.resetAt;
el('status').textContent=data.error?data.error.message:'Ready';el('status').className=data.error?'error':'';
el('meeting').replaceChildren();data.meetings.forEach(m=>{const o=node('option',m.title+' · '+m.created_at);o.value=m.id;el('meeting').append(o)});if(data.selected)el('meeting').value=data.selected;
el('original').textContent=data.source?data.source.text+'\n\nReference: '+data.source.referenceAt:'No source yet.';el('state').textContent=pretty(data.state);el('receipt').textContent=pretty(data.result);
const items=[...(data.state?.actionItems||[]),...(data.state?.decisions||[]),...(data.state?.openQuestions||[]),...(data.state?.risks||[])];const oldItem=el('item').value;el('items').replaceChildren();el('item').replaceChildren();if(!items.length)el('items').append(node('p','No extracted items yet.'));
items.forEach(i=>{const text=i.description||i.statement||i.question;const div=node('div','','item');div.append(node('p',text),node('small',(i.status||'open')+(i.ownerId?' · '+i.ownerId:'')+(i.dueDate?.normalizedDate?' · due '+i.dueDate.normalizedDate:'')));el('items').append(div);if(i.description||data.state?.decisions.some(d=>d.id===i.id)){const o=node('option',text);o.value=i.id;el('item').append(o)}});if(items.some(i=>i.id===oldItem))el('item').value=oldItem;
const r=data.result;el('answer').textContent=r?.answer?.text||'';el('citations').replaceChildren();(r?.answer?.evidence||[]).forEach(e=>{const d=document.createElement('details');d.append(node('summary','Source · '+e.author.displayName),node('pre',e.text||'(unavailable)'));el('citations').append(d)});
const errors=r?.errors||[];el('outcome').textContent=data.error?data.error.message:errors.length?errors.map(e=>e.message||e.code).join('\n'):r?.message||r?.analysisStatus? r?.message||'Analysis: '+r.analysisStatus:r?.answer?'AI answer received':r?'Operation completed':'No operation yet.';el('outcome').className=data.error||errors.length?'error':'';
}
async function call(body){if(busy)return;lock(true);el('status').textContent='Working…';try{const response=await fetch('/api/command',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const data=await response.json();if(!response.ok)throw new Error(data.error||'Local request failed');render(data)}catch{el('status').textContent='Could not reach the local server. Do not resubmit automatically; refresh to inspect retained state and usage.';el('status').className='error'}finally{lock(false)}}
el('connect').onclick=()=>{const apiKey=el('key').value;el('key').value='';return call({type:'connect',apiKey})};el('disconnect').onclick=()=>call({type:'disconnect'});
el('sample').onclick=()=>{el('source').value='Jakob: I own Luma. I will prepare a local test by Monday.\nFabius: We could use a VPS later, but we have not decided on hosting.\nJulius: Keep AI usage under $30 per month for now.\nPhilipp: I can review the website copy if needed; this is not yet assigned.'};
el('analyze').onclick=()=>call({type:'analyze',title:el('title').value,text:el('source').value});el('ask').onclick=()=>call({type:'ask',text:el('question').value});el('question').onkeydown=e=>{if(e.key==='Enter')el('ask').click()};el('select').onclick=()=>call({type:'select',meetingId:el('meeting').value});el('replay').onclick=()=>call({type:'replay'});el('conclude').onclick=()=>call({type:'conclude'});
['confirm','reject'].forEach(action=>el(action).onclick=()=>call({type:'judge',itemId:el('item').value,action}));el('change-owner').onclick=()=>call({type:'judge',itemId:el('item').value,action:'owner',owner:el('owner').value});
lock(true);fetch('/api/state',{method:'POST',headers:{'Content-Type':'application/json'},body:'{}'}).then(r=>{if(!r.ok)throw new Error();return r.json()}).then(render).catch(()=>{el('status').textContent='Local server unavailable. Check the terminal.'}).finally(()=>lock(false));
</script></body></html>`;
